version: "3"

networks:
  default:
    driver: bridge
    name: database

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - ./.data/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD:
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes:
      - ./.data/phpmyadmin:/phpmyadmin:ro
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    working_dir: /app
    ports:
      - 80:80
    depends_on:
      - phpmyadmin
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    depends_on:
      - mariadb
    restart: unless-stopped
    volumes:
      - ./.data/phpmyadmin:/var/www/html
